import './Home.css';

const Home = () => (
	<div className='Home'>
		<h1>Hi, I'm Kai,</h1>
		<p className='tagline'>Software Developer / Student</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis ultrices urna, sed rhoncus dui. Mauris in lorem ut felis blandit posuere. Maecenas bibendum magna quis fermentum dapibus. Proin bibendum velit ac ultricies vehicula. Aliquam porttitor accumsan arcu ut faucibus. Vestibulum sed arcu consequat, imperdiet neque vel, malesuada libero. In in nisl laoreet, consectetur odio pretium, tempor est. Fusce lacinia gravida lectus quis scelerisque. Curabitur a purus gravida, suscipit turpis quis, tincidunt ipsum. Donec eleifend tincidunt nibh, et dapibus justo. Quisque accumsan congue orci, id tristique massa iaculis in. Donec in leo odio. Proin sed nisi dapibus, accumsan ipsum posuere, dignissim ipsum. Pellentesque vestibulum, libero sed elementum condimentum, lectus nisl mollis dolor, nec eleifend ante purus non leo. Vestibulum ultrices tincidunt tortor, et luctus nibh vulputate eu. Proin nunc erat, mollis vel magna eget, ullamcorper tincidunt augue.</p>
		<p>Etiam neque nisi, ullamcorper ut posuere a, rhoncus gravida nibh. Vivamus lectus magna, vehicula eget ligula et, lobortis sodales nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean in elementum massa. In porttitor maximus aliquet. Mauris lacinia et velit eu venenatis. In accumsan id est at rutrum. Aliquam tempor pharetra justo. Proin pulvinar, sem ac maximus egestas, lectus justo maximus velit, quis luctus diam est id felis. Nullam rhoncus enim ac lectus malesuada posuere. Donec efficitur fermentum nibh ut bibendum. Morbi sed risus in ipsum aliquet dignissim id non velit. Aliquam sodales hendrerit arcu, vitae porttitor dui. Nunc aliquam eget ex at bibendum. Praesent velit metus, fermentum accumsan vulputate id, dictum a dui.</p>
		<p>In et justo non quam rhoncus pellentesque. Maecenas eleifend risus eu tristique sodales. Sed efficitur tortor nec ex tempus ultricies. Etiam lacus quam, tempus quis tempor at, convallis eget turpis. Mauris erat ipsum, imperdiet id porttitor at, accumsan sed nunc. In at scelerisque dolor. Sed et commodo magna. Quisque lobortis massa vitae est ullamcorper faucibus. Quisque venenatis est pretium, facilisis massa sit amet, egestas nunc.</p>
		<p>Nullam tempor faucibus laoreet. In tincidunt odio nec orci bibendum, id auctor sapien tempor. Donec porta ultricies finibus. Etiam sed malesuada dui, non faucibus felis. Duis elementum, quam eu porta condimentum, dolor augue bibendum ante, quis viverra orci risus nec ipsum. Aenean in lobortis neque, sed tempus quam. Ut ipsum diam, pharetra nec molestie eu, interdum a urna. Quisque ut lectus risus. Nam pulvinar lacinia pellentesque.</p>
		<p>Ut sollicitudin bibendum nibh, non condimentum justo gravida sed. Morbi pretium luctus elit, in viverra lacus vestibulum vitae. Nullam ullamcorper fermentum tellus, quis tempor mi venenatis sit amet. Mauris volutpat diam convallis neque convallis, non pulvinar metus finibus. Fusce sollicitudin libero id tortor lobortis vehicula. Ut lectus purus, auctor sit amet interdum ac, vulputate non nunc. Aliquam laoreet tincidunt orci, vel commodo orci eleifend non. Proin eget condimentum magna. In luctus magna eget ornare malesuada. Suspendisse in lacus a erat vulputate ullamcorper suscipit sit amet felis. Nam a nisl condimentum, sollicitudin magna at, scelerisque diam. Donec dignissim vitae augue at laoreet. Vestibulum efficitur est quis tincidunt dictum. Fusce bibendum luctus feugiat.</p>
	</div>
)

export default Home;
